// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Q{!yX{k`+}U|nBMqf6?)":
            case "Hero":return img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f 2 2 f f f f f . . 
. . f f e 2 e 2 2 e 2 e f f . . 
. . f e 2 f 2 f f 2 f 2 e f . . 
. . f f f 2 2 e e 2 2 f f f . . 
. f f e f 2 f e e f 2 f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f . . . 
. . e 4 f f f f f f f f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "jrH=)s|@bclMGTE#_lTR":
            case "Raft":return img`
................................................................
................................................................
................................................................
..................bbb......bbb......bbb......bbb................
................bbdddb....bdddb....bdddb....bdddbb..............
...............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb.............
..............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb............
.............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb...........
.............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb...........
.............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb...........
.............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb............
.............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc............
.............eeffbdddceeefbdddbceefbdddcce.eedddbcce............
.............eeeefccce.eeeffccceeeefccceee.eefccceee............
.............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee............
.............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee............
.............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee............
..............feeeeeee..feeeeeeeefeeeeeeee..feeeeeee............
..............fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee............
..............eeeeeeeee.eeeeeeeeeeeeeeeeee.eeeeeeeee............
..............ceeeeeeee.ceeeeeeeeceeeeeeee.eceeeeeee............
..............ceeeeeeee.ceeeeeeeeceeeeeeee.eceeeeeee............
..............eeeeeeeee.eeeeeeeeeeeeeeeeee.eeeeeeeee............
..............eeeeeeeef.eeeeeeeeeeeeeeeeee.feeeeeeee............
..............eeeeeeeef.eeeeeeeeeeeeeeeeee.feeeeeeee............
..............eeeeeeeef.eeeeeeeeceeeeeeeec.feeeeeeec............
..............ceeeeeeef.ceeeeeeecceeeeeeec.fceeeeeec............
..............ceeeeeeef.ceeeeeeefceeeeeeef.fceeeeeef............
..............feeeeeeee.feeeeeeeffeeeeeeef.efeeeeeef............
..............feeeeeeee.feeeeeeeffeeeeeeef.efeeeeeef............
..............eeeeeeeee.eeeeeeeeeeeeeeeeee.eeeeeeeee............
..............eeeeeeeee.eeeeeeeeeeeeeeeeee.eeeeeeeee............
..............eeeeeeeee.eeeeeeeeeeeeeeeeee..eeeeeeee............
..............eeeeeeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee............
..............eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee............
..............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece............
..............eeceeeee..eeeeeeeceeeeeeeece..eeeeeece............
..............eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe............
..............eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe............
..............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece............
..............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece............
..............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee............
..............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee............
..............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee............
..............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee............
..............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee............
..............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee............
..............fcceeeec..fceeeeeeefceeeecee..feeeecee............
..............fccceecc..fcceececefcceeccce..feeeecce............
..............fcceeccc..fceeececcfceeccccc..feececcc............
..............fccceccc..fcceececcfcceccccc..feececcc............
..............fccccece..fccccceccfcccececc..fcceeecc............
..............fccccccc..fcccccccffcccccccf..fccccccf............
..............cccccccc..cccccccccccccccccc..cccccccc............
..............cccccccc..cccccccccccccccccc..cccccccc............
..............cccccccc..cccccccccccccccccc..cccccccc............
..............cccccccc..cccccccccccccccccc..cccccccc............
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "~3/T0I6*G%:BK)55ILlg":
            case "RaftWithPlayer":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
.................bbb......bbb......bbb......bbb.................
...............bbdddb....bdddb....bdddb....bdddbb...............
..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
.............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
............eeeefccce.eeeffccceeeefccceee.eefccceee.............
............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
.............feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
.............fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
.............eeeeeeeee.eeeeeeeeeeeeeeeeee.eeeeeeeee.............
.............ceeeefffe.ceeeeeeeeceeeeeeee.eceeeeeee.............
.............ceeffeeeffceeeeeeeeceeeeeeee.eceeeeeee.............
.............eefeeefeeefeeeeeeeeeeeeeeeee.eeeeeeeee.............
.............efffff2fffffeeeeeeeeeeeeeeee.feeeeeeee.............
.............effe2e2e2effeeeeeeeeeeeeeeee.feeeeeeee.............
.............efff22e22fffeeeeeeceeeeeeeec.feeeeeeec.............
.............ffef2fef2fefeeeeeecceeeeeeec.fceeeeeec.............
.............feeffeeefeeeeeeeeefceeeeeeef.fceeeeeef.............
.............ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
.............fe4fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
.............e4df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
.............e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
.............eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
.............eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
.............eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
.............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
.............eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
.............eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
.............eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
.............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
.............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
.............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
.............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
.............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
.............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
.............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
.............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
.............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
.............fccceecc..fcceececefcceeccce..feeeecce.............
.............fcceeccc..fceeececcfceeccccc..feececcc.............
.............fccceccc..fcceececcfcceccccc..feececcc.............
.............fccccece..fccccceccfcccececc..fcceeecc.............
.............fccccccc..fcccccccffcccccccf..fccccccf.............
.............cccccccc..cccccccccccccccccc..cccccccc.............
.............cccccccc..cccccccccccccccccc..cccccccc.............
.............cccccccc..cccccccccccccccccc..cccccccc.............
.............cccccccc..cccccccccccccccccc..cccccccc.............
................................................................
................................................................
................................................................
................................................................
................................................................
`;
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . 1 . . . . . . 1 . . . . . 
. . 1 1 1 . . . . 1 d 1 . . . . 
. . 1 1 1 . . . . d 1 d . . . . 
. . 1 d 1 . . . . 1 1 1 . . . . 
. . d 1 1 d 1 . 1 1 1 1 . . . . 
. . 1 1 1 d d 1 1 1 1 1 . . . . 
. . 1 1 1 1 d d 1 1 1 1 . . . . 
. . 1 1 1 1 1 1 1 1 1 . . . . . 
. . 1 1 1 1 1 1 1 1 1 . . . . . 
. . 1 1 1 1 1 1 1 1 1 . . . . . 
. . . 1 1 1 1 1 1 1 . . . . . . 
. . . . 1 1 1 1 d d . . . . . . 
. . . . . 1 1 d 1 . . . . . . . 
. . . . . . 1 1 . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "myImage0":return img`
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 d 1 1 9 9 9 9 9 9 9 
9 9 9 9 9 9 d 1 1 9 9 9 9 9 9 9 
9 9 9 9 9 9 1 1 1 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
`;
            case "image3":
            case "myImage1":return img`
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 1 2 9 9 9 9 9 
9 9 9 9 9 9 9 9 2 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 2 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 2 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 2 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 1 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 2 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
`;
            case "image4":
            case "myImage2":return img`
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
9 9 9 9 9 9 8 8 8 8 9 9 9 9 9 9 
9 9 9 9 9 9 9 d d 9 9 9 9 9 9 9 
9 9 9 9 9 9 9 d d 9 9 9 9 9 9 9 
9 9 9 9 9 9 d 1 1 d 9 9 9 9 9 9 
9 9 9 9 9 d 1 1 1 1 d 9 9 9 9 9 
9 9 9 9 9 d 9 9 1 1 d 9 9 9 9 9 
9 9 9 9 9 d 1 9 9 9 d 9 9 9 9 9 
9 9 9 9 9 d 1 9 1 9 d 9 9 9 9 9 
9 9 9 9 9 d 9 1 9 1 d 9 9 9 9 9 
9 9 9 9 9 d 1 9 1 9 d 9 9 9 9 9 
9 9 9 9 9 d 9 9 9 9 d 9 9 9 9 9 
9 9 9 9 9 d 1 1 1 1 d 9 9 9 9 9 
9 9 9 9 9 d 1 1 1 1 d 9 9 9 9 9 
9 9 9 9 9 d d d d d d 9 9 9 9 9 
9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
`;
            case "image5":
            case "RaftFlippedRight":return img`
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
...............................................cfceeeccbb.......
.......ccccffffffccceeeeeeeeeeeeeeffcceeeecceffceeeefbdddb......
.......cccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeceeeeefbdbbbdb.....
.......cccccccccceeeeeeeeccceeeeeeeeeeeeeeeeeeeeeeefdbbdbbdb....
.......ccccccceceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefbdbdbdbdb....
.......cccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......cccccecceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......ccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......cccccecccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbbdbbdb....
.................fffeee.......feeeeefffffeeeef.....eedbdbdb.....
...............................................cfceeedbbbb......
.......ccccffffffccceeeeeeeeeeeeeeffcceeeecceffceeeefbdddb......
.......cccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeceeeeefbdbbbdb.....
.......ccccccceceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefbdbdbdbdb....
.......cccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefdbdbdbdbdb...
.......cccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......ccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......ccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecbdbdbdbdb....
.......ccccccccceeeeeeeccffcceeeeeeeeeeeeeeeeeeeeeecbdbbbdb.....
.......ccccfccceeeeeeeeeeeeeeeeeeefffcceeeeeeeeeeeeecbdddb......
.......ccccffffffccceeeeeeeeeeeeeeffcceeeecceffceeeefbdddb......
.......cccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeceeeeefbdbbbdb.....
.......ccccccceceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefbdbdbdbdb....
.......cccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......cccccecceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......ccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......cccccecccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbbdbbdb....
.......ccccccccceeeeeeeccffcceeeeeeeeeeeeeeeeeeeeeecbdbbbdb.....
.......ccccfccceeeeeeeeeeeeeeeeeeefffcceeeeeeeeeeeeecbdddb......
.................fffeee.......f......................bbbbb......
................................eeeefffffeeeef.cfceeedbdbdb.....
.......ccccffffffccceeeeeeeeeeeeeeffcceeeecceffceeeefbdbdbdb....
.......cccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefdbdbdbdbdb...
.......cccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......cccccecceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbdbdbdbdb...
.......ccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecbdbdbdbdb....
.......cccccecccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecdbbdbbdb....
.......ccccccccceeeeeeeccffcceeeeeeeeeeeeeeeeeeeeeecbdbbbdb.....
.......ccccfccceeeeeeeeeeeeeeeeeeefffcceeeeeeeeeeeeecbdddb......
......................................................bbb.......
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
