namespace SpriteKind {
    export const Raft = SpriteKind.create()
    export const Trigger = SpriteKind.create()
}
scene.onHitWall(SpriteKind.Raft, function (sprite, location) {
    if (currentTileMap == "Sea") {
        canEnterVillage = true
    }
    if (currentTileMap == "Village") {
        canEnterRaft = true
    }
    if (currentTileMap == "River") {
        canEnterRiver = true
    }
})


scene.onOverlapTile(SpriteKind.Player, sprites.castle.tileDarkGrass3, function (sprite, location) {
    canEnterRaft = true
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.tileGrass1, function (sprite, location) {
    canEnterRaft = false
})


function loadRiver2 () {
	
}
function loadVillage () {
    controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
        if (canEnterRaft == true) {
            currentTileMap = "River"
            tiles.loadMap(tiles.createMap(assets.tilemap`River`))
            sprites.destroyAllSpritesOfKind(SpriteKind.Raft)
            sprites.destroyAllSpritesOfKind(SpriteKind.Player)
            enterRaftingMode()
            canEnterRiver = false
            loadRiver()
        }

    })
}
function loadRiver () {
    controller.A.onEvent(ControllerButtonEvent.Pressed, function(){

        if (canEnterRaft == true){
            currentTileMap = "River2"
            tiles.loadMap(tiles.createMap(assets.tilemap`River2`))
            sprites.destroyAllSpritesOfKind(SpriteKind.Raft)
            sprites.destroyAllSpritesOfKind(SpriteKind.Player)
            enterRaftingMode()
            canEnterRiver = false
            loadRiver2()
        }

    })
}
function loadHeroHouse () {
    spawnHero()
    spawnRaft()

    controller.B.onEvent(ControllerButtonEvent.Pressed, function(){
        if (canEnterRaft == true){ 
            currentTileMap = "Sea"
            tiles.loadMap(tiles.createMap(assets.tilemap`Sea`))
            sprites.destroyAllSpritesOfKind(SpriteKind.Raft)
            sprites.destroyAllSpritesOfKind(SpriteKind.Player)
            enterRaftingMode()
            canEnterRaft = false
            loadSea()
        }
    })
}
function loadSea () {
    controller.B.onEvent(ControllerButtonEvent.Pressed, function(){
        if (canEnterVillage == true) {
            currentTileMap = "Village"
            tiles.loadMap(tiles.createMap(assets.tilemap`Village`))
            sprites.destroyAllSpritesOfKind(SpriteKind.Raft)
            sprites.destroyAllSpritesOfKind(SpriteKind.Player)
            spawnHero()
            canEnterVillage = false
            loadVillage()
        }
        
    })
}
function spawnHero () {
    hero = sprites.create(assets.image`Hero`, SpriteKind.Player)
    tiles.placeOnRandomTile(hero, assets.tile`myTile17`)
    tiles.coverAllTiles(assets.tile`myTile17`, sprites.castle.tileGrass2)
    enterWalkingMode()
}
function spawnRaft () {
    raft = sprites.create(assets.image`RaftFlippedRight`, 0)
    tiles.placeOnRandomTile(raft, assets.tile`myTile16`)
    tiles.replaceAllTiles(assets.tile`myTile16`, assets.tile`myTile3`)
}
function enterWalkingMode () {
    sprites.destroyAllSpritesOfKind(SpriteKind.Raft)
    scene.cameraFollowSprite(hero)
    controller.moveSprite(hero, heroVel, heroVel)
    characterAnimations.loopFrames(
    hero,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f f 2 f e f . . 
        . . f f f 2 f e e 2 2 f f f . . 
        . . f e 2 f f e e 2 f e e f . . 
        . f f e f f e e e f e e e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . . e f f f f f f f f 4 e . . 
        . . . 4 f 2 2 2 2 2 e d d 4 . . 
        . . . e f f f f f f e e 4 . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e f 2 f f f 2 f 2 e f . . 
        . . f f f 2 2 e e f 2 f f f . . 
        . . f e e f 2 e e f f 2 e f . . 
        . f f e e e f e e e f f e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f e . . . 
        . . 4 d d e 2 2 2 2 2 f 4 . . . 
        . . . 4 e e f f f f f f e . . . 
        . . . . . . . . . f f f . . . . 
        `],
    100,
    characterAnimations.rule(Predicate.MovingUp)
    )
    characterAnimations.loopFrames(
    hero,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . . f e 4 d d d d 4 e f e . . 
        . . f e f 2 2 2 2 e d d 4 e . . 
        . . e 4 f 2 2 2 2 e d d e . . . 
        . . . . f 4 4 5 5 f e e . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . e f e 4 d d d d 4 e f . . . 
        . . e 4 d d e 2 2 2 2 f e f . . 
        . . . e d d e 2 2 2 2 f 4 e . . 
        . . . . e e f 5 5 4 4 f . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . . . . . f f f . . . . 
        `],
    100,
    characterAnimations.rule(Predicate.MovingDown)
    )
    characterAnimations.loopFrames(
    hero,
    [img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e e e d d d f . . . 
        . . . . . f 4 d d e 4 e f . . . 
        . . . . . f e d d e 2 2 f . . . 
        . . . . f f f e e f 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `,img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . 4 d d e 4 4 4 e f . . . 
        . . . . e d d e 2 2 2 2 f . . . 
        . . . . f e e f 4 4 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `],
    100,
    characterAnimations.rule(Predicate.MovingRight)
    )
    characterAnimations.loopFrames(
    hero,
    [img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d e e e e e f . . . 
        . . . f e 4 e d d 4 f . . . . . 
        . . . f 2 2 e d d e f . . . . . 
        . . f f 5 5 f e e f f f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `,img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e d d 4 . . . . 
        . . . f 2 2 2 2 e d d e . . . . 
        . . f f 5 5 4 4 f e e f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `],
    100,
    characterAnimations.rule(Predicate.MovingLeft)
    )
}
function enterRaftingMode () {
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    sprites.destroyAllSpritesOfKind(SpriteKind.Raft)
    raft = sprites.create(assets.image`RaftWithPlayer`, SpriteKind.Raft)
    tiles.placeOnRandomTile(raft, assets.tile`myTile16`)
    tiles.replaceAllTiles(assets.tile`myTile16`, assets.tile`myTile3`)
    scene.cameraFollowSprite(raft)
    controller.moveSprite(raft, raftVel, raftVel)
    characterAnimations.loopFrames(
    raft,
    [img`
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .................bbb......bbb......bbb......bbb.................
        ...............bbdddb....bdddb....bdddb....bdddbb...............
        ..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
        .............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
        ............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
        ............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
        ............eeeefccce.eeeffccceeeefccceee.eefccceee.............
        ............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
        ............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
        ............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
        .............feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
        .............fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
        .............eeeeeeeee.eeee44eeeeeeeeeeee.eeeeeeeee.............
        .............ceeeefffe.cee444eeeceeeeeeee.eceeeeeee.............
        .............ceeffeeeffc4444eeeeceeeeeeee.eceeeeeee.............
        .............eefeeefeeef44eeeeeeeeeeeeeee.eeeeeeeee.............
        .............efffff2fffffeeeeeeeeeeeeeeee.feeeeeeee.............
        .............effe2e2e2effeeeeeeeeeeeeeeee.feeeeeeee.............
        .............efff22e22fffeeeeeeceeeeeeeec.feeeeeeec.............
        .............ffef2fef2fefeeeeeecceeeeeeec.fceeeeeec.............
        .............feeffeeefeeeeeeeeefceeeeeeef.fceeeeeef.............
        .............ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
        ............4f44fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
        ............444df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
        ...........44e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
        ..........444eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .....44..444.eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
        ....444.444..eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
        ...4444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..44444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ...4444......eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
        .............fccceecc..fcceececefcceeccce..feeeecce.............
        .............fcceeccc..fceeececcfceeccccc..feececcc.............
        .............fccceccc..fcceececcfcceccccc..feececcc.............
        .............fccccece..fccccceccfcccececc..fcceeecc.............
        .............fccccccc..fcccccccffcccccccf..fccccccf.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        `,img`
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .................bbb......bbb......bbb......bbb.................
        ...............bbdddb....bdddb....bdddb....bdddbb...............
        ..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
        .............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
        ............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
        ............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
        ............eeeefccce.eeeffccceeeefccceee.eefccceee.............
        ............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
        ............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
        ............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
        .....4444444.feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
        .....4444444.fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
        .....44444444eeeeeeeee.eeeeeeeeeeeeeeeeee.eeeeeeeee.............
        .....4444444444eeefffe.ceeeeeeeeceeeeeeee.eceeeeeee.............
        .....44444444444ffeeeffceeeeeeeeceeeeeeee.eceeeeeee.............
        .....444444..e4feeefeeefeeeeeeeeeeeeeeeee.eeeeeeeee.............
        ......4444...efffff2fffff4eeeeeeeeeeeeeee.feeeeeeee.............
        .......444...effe2e2e2eff444eeeeeeeeeeeee.feeeeeeee.............
        .......444...efff22e22fff4444eeceeeeeeeec.feeeeeeec.............
        .............ffef2fef2fefee4eeecceeeeeeec.fceeeeeec.............
        ......1......feeffeeefeeeeeeeeefceeeeeeef.fceeeeeef.............
        .....1..1...4ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
        .....1.1.....f44fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
        .....1.1.....44df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
        .....1.1.....e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
        .....1.1.....eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .....1.1.....eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
        .......1.....eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .......1.....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .......1.....eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .............eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        .............eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        .............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
        .............fccceecc..fcceececefcceeccce..feeeecce.............
        .............fcceeccc..fceeececcfceeccccc..feececcc.............
        .............fccceccc..fcceececcfcceccccc..feececcc.............
        .............fccccece..fccccceccfcccececc..fcceeecc.............
        .............fccccccc..fcccccccffcccccccf..fccccccf.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        `],
    300,
    characterAnimations.rule(Predicate.MovingDown)
    )
    characterAnimations.loopFrames(
    raft,
    [img`
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .................bbb......bbb......bbb......bbb.................
        ...............bbdddb....bdddb....bdddb....bdddbb...............
        ..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
        .............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
        ............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
        ............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
        ............eeeefccce.eeeffccceeeefccceee.eefccceee.............
        ............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
        ............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
        ............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
        .....4444444.feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
        .....4444444.fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
        .....44444444eeeeeeeee.eeeeeeeeeeeeeeeeee.eeeeeeeee.............
        .....4444444444eeefffe.ceeeeeeeeceeeeeeee.eceeeeeee.............
        .....44444444444ffeeeffceeeeeeeeceeeeeeee.eceeeeeee.............
        .....444444..e4feeefeeefeeeeeeeeeeeeeeeee.eeeeeeeee.............
        ......4444...efffff2fffff4eeeeeeeeeeeeeee.feeeeeeee.............
        .......444...effe2e2e2eff444eeeeeeeeeeeee.feeeeeeee.............
        .......444...efff22e22fff4444eeceeeeeeeec.feeeeeeec.............
        .............ffef2fef2fefee4eeecceeeeeeec.fceeeeeec.............
        .............feeffeeefeeeeeeeeefceeeeeeef.fceeeeeef.............
        ............4ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
        .............f44fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
        .............44df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
        .............e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
        .............eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .............eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
        .............eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .............eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .............eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        .............eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        .............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .............eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
        .............fccceecc..fcceececefcceeccce..feeeecce.............
        .............fcceeccc..fceeececcfceeccccc..feececcc.............
        .............fccceccc..fcceececcfcceccccc..feececcc.............
        .............fccccece..fccccceccfcccececc..fcceeecc.............
        .............fccccccc..fcccccccffcccccccf..fccccccf.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        `,img`
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .................bbb......bbb......bbb......bbb.................
        ...............bbdddb....bdddb....bdddb....bdddbb...............
        ..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
        .............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
        ............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
        ............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
        ............eeeefccce.eeeffccceeeefccceee.eefccceee.............
        ............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
        ............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
        ............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
        .............feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
        .............fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
        .............eeeeeeeee.eeee44eeeeeeeeeeee.eeeeeeeee.............
        .............ceeeefffe.cee444eeeceeeeeeee.eceeeeeee.............
        .....1.......ceeffeeeffc4444eeeeceeeeeeee.eceeeeeee.............
        ..1..1.......eefeeefeeef44eeeeeeeeeeeeeee.eeeeeeeee.............
        ..1..1.......efffff2fffffeeeeeeeeeeeeeeee.feeeeeeee.............
        ..1..1.......effe2e2e2effeeeeeeeeeeeeeeee.feeeeeeee.............
        ..1..1.......efff22e22fffeeeeeeceeeeeeeec.feeeeeeec.............
        ..1..1.......ffef2fef2fefeeeeeecceeeeeeec.fceeeeeec.............
        ..1..1.......feeffeeefeeeeeeeeefceeeeeeef.fceeeeeef.............
        ..1..1.......ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
        ..1..1......4f44fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
        ..1..1......444df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
        ..1.1......44e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
        ..1.......444eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .1...44..444.eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
        ....444.444..eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
        ...4444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..44444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ...4444......eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
        .............fccceecc..fcceececefcceeccce..feeeecce.............
        .............fcceeccc..fceeececcfceeccccc..feececcc.............
        .............fccceccc..fcceececcfcceccccc..feececcc.............
        .............fccccece..fccccceccfcccececc..fcceeecc.............
        .............fccccccc..fcccccccffcccccccf..fccccccf.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        `],
    300,
    characterAnimations.rule(Predicate.MovingUp)
    )
    characterAnimations.loopFrames(
    raft,
    [img`
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .................bbb......bbb......bbb......bbb.................
        ...............bbdddb....bdddb....bdddb....bdddbb...............
        ..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
        .............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
        ............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
        ............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
        ............eeeefccce.eeeffccceeeefccceee.eefccceee.............
        ............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
        ............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
        ............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
        .............feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
        .............fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
        .............eeeeeeeee.eeee44eeeeeeeeeeee.eeeeeeeee.............
        .............ceeeefffe.cee444eeeceeeeeeee.eceeeeeee.............
        .............ceeffeeeffc4444eeeeceeeeeeee.eceeeeeee.............
        .............eefeeefeeef44eeeeeeeeeeeeeee.eeeeeeeee.............
        .............efffff2fffffeeeeeeeeeeeeeeee.feeeeeeee.............
        .............effe2e2e2effeeeeeeeeeeeeeeee.feeeeeeee.............
        .............efff22e22fffeeeeeeceeeeeeeec.feeeeeeec.............
        .............ffef2fef2fefeeeeeecceeeeeeec.fceeeeeec.............
        .............feeffeeefeefeeeeeefceeeeeeef.fceeeeeef.............
        .............ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
        ............4f44fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
        ............444df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
        ...........44e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
        ..........444eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .....44..444.eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
        ....444.444..eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
        ...4444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..44444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ...4444......eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
        .............fccceecc..fcceececefcceeccce..feeeecce.............
        .............fcceeccc..fceeececcfceeccccc..feececcc.............
        .............fccceccc..fcceececcfcceccccc..feececcc.............
        .............fccccece..fccccceccfcccececc..fcceeecc.............
        .............fccccccc..fcccccccffcccccccf..fccccccf.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        `,img`
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .................bbb......bbb......bbb......bbb.................
        ...............bbdddb....bdddb....bdddb....bdddbb...............
        ..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
        .............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
        ............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
        ............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
        ............eeeefccce.eeeffccceeeefccceee.eefccceee.............
        ............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
        ............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
        ............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
        .............feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
        .............fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeee.eeeeeeeee.............
        .............ceeeefffe.ee44eeeeeceeeeeeee.eceeeeeee.............
        .............ceeffeeeff4444eeeeeceeeeeeee.eceeeeeee.............
        .............eefeeefeeef4eeeeeeeeeeeeeeee.eeeeeeeee.............
        .............efffff2fffffeeeeeeeeeeeeeeee.feeeeeeee.............
        .............effe2e2e2effeeeeeeeeeeeeeeee.feeeeeeee.............
        .............efff22e22fffeeeeeeceeeeeeeec.feeeeeeec.............
        .............ffef2fef2fefeeeeeecceeeeeeec.fceeeeeec.............
        .............feeffeeefeefeeeeeefceeeeeeef.fceeeeeef.............
        .............ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
        .............f44fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
        ............444df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
        ...........44e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
        ..........44.eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .........444.eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
        ........444..eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
        ...44..444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..444.444....eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .4444444.....eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        4444444......eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        444444444....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        444444444....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        44444444.....eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        4444444......eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .4444........eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
        .............fccceecc..fcceececefcceeccce..feeeecce.............
        .............fcceeccc..fceeececcfceeccccc..feececcc.............
        .............fccceccc..fcceececcfcceccccc..feececcc.............
        .............fccccece..fccccceccfcccececc..fcceeecc.............
        .............fccccccc..fcccccccffcccccccf..fccccccf.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        `],
    300,
    characterAnimations.rule(Predicate.MovingRight)
    )
    characterAnimations.loopFrames(
    raft,
    [img`
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .................bbb......bbb......bbb......bbb.................
        ...............bbdddb....bdddb....bdddb....bdddbb...............
        ..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
        .............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
        ............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
        ............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
        ............eeeefccce.eeeffccceeeefccceee.eefccceee.............
        ............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
        ............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
        ............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
        .............feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
        .............fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeee.eeeeeeeee.............
        .............ceeeefffe.ee44eeeeeceeeeeeee.eceeeeeee.............
        .............ceeffeeeff4444eeeeeceeeeeeee.eceeeeeee.............
        .............eefeeefeeef4eeeeeeeeeeeeeeee.eeeeeeeee.............
        .............efffff2fffffeeeeeeeeeeeeeeee.feeeeeeee.............
        .............effe2e2e2effeeeeeeeeeeeeeeee.feeeeeeee.............
        .............efff22e22fffeeeeeeceeeeeeeec.feeeeeeec.............
        .............ffef2fef2fefeeeeeecceeeeeeec.fceeeeeec.............
        .............feeffeeefeefeeeeeefceeeeeeef.fceeeeeef.............
        .............ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
        .............f44fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
        ............444df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
        ...........44e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
        ..........44.eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .........444.eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
        ........444..eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
        ...44..444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..444.444....eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        .4444444.....eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        4444444......eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        444444444....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        444444444....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        44444444.....eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        4444444......eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .4444........eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
        .............fccceecc..fcceececefcceeccce..feeeecce.............
        .............fcceeccc..fceeececcfceeccccc..feececcc.............
        .............fccceccc..fcceececcfcceccccc..feececcc.............
        .............fccccece..fccccceccfcccececc..fcceeecc.............
        .............fccccccc..fcccccccffcccccccf..fccccccf.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        `,img`
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .................bbb......bbb......bbb......bbb.................
        ...............bbdddb....bdddb....bdddb....bdddbb...............
        ..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
        .............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
        ............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
        ............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
        ............eeeefccce.eeeffccceeeefccceee.eefccceee.............
        ............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
        ............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
        ............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
        .............feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
        .............fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
        .............eeeeeeeee.eeee44eeeeeeeeeeee.eeeeeeeee.............
        .............ceeeefffe.cee444eeeceeeeeeee.eceeeeeee.............
        .............ceeffeeeffc4444eeeeceeeeeeee.eceeeeeee.............
        .............eefeeefeeef44eeeeeeeeeeeeeee.eeeeeeeee.............
        .............efffff2fffffeeeeeeeeeeeeeeee.feeeeeeee.............
        .............effe2e2e2effeeeeeeeeeeeeeeee.feeeeeeee.............
        .............efff22e22fffeeeeeeceeeeeeeec.feeeeeeec.............
        .............ffef2fef2fefeeeeeecceeeeeeec.fceeeeeec.............
        .............feeffeeefeefeeeeeefceeeeeeef.fceeeeeef.............
        .............ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
        ............4f44fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
        ............444df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
        ...........44e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
        ..........444eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .....44..444.eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
        ....444.444..eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
        ...4444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..44444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ...4444......eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
        .............fccceecc..fcceececefcceeccce..feeeecce.............
        .............fcceeccc..fceeececcfceeccccc..feececcc.............
        .............fccceccc..fcceececcfcceccccc..feececcc.............
        .............fccccece..fccccceccfcccececc..fcceeecc.............
        .............fccccccc..fcccccccffcccccccf..fccccccf.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        `],
    300,
    characterAnimations.rule(Predicate.MovingLeft)
    )
    characterAnimations.runFrames(
    raft,
    [img`
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        .................bbb......bbb......bbb......bbb.................
        ...............bbdddb....bdddb....bdddb....bdddbb...............
        ..............bddbbbdb..bdbbbdb..bdbbbdb..bdbbbddb..............
        .............bdbbdddbdbbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............bdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............bdbdbdddddbdbbdddbbddbbddddbdbdbdddbdbdb............
        ............cdbbdbbbbbbdbdbbbdbddbdbbbbbdbbdbbbdbbdb............
        ............cbdbbdddbddbdbdddbdbbdbdddbdbbdbdddbbdb.............
        ............efbddbbbdeefbdbbbdbcfbdbbbdbc.efbbbddbc.............
        ............eeffbdddceeefbdddbceefbdddcce.eedddbcce.............
        ............eeeefccce.eeeffccceeeefccceee.eefccceee.............
        ............ceeeeeeee.ceeeeeeeeeeeeeeeeee.ceeeeeeee.............
        ............feeeeeeee.feeeeeeeeeeeeeeeeee.feeeeeeee.............
        ............cceeeeeee.cceeeeeeeeceeeeeeee.cceeeeeee.............
        .............feeeeeee..feeeeeeeefeeeeeeee..feeeeeee.............
        .............fceeeeeef.fceeeeeeefceeeeeee.ffeeeeeee.............
        .............eeeeeeeee.eeee44eeeeeeeeeeee.eeeeeeeee.............
        .............ceeeefffe.cee444eeeceeeeeeee.eceeeeeee.............
        .............ceeffeeeffc4444eeeeceeeeeeee.eceeeeeee.............
        .............eefeeefeeef44eeeeeeeeeeeeeee.eeeeeeeee.............
        .............efffff2fffffeeeeeeeeeeeeeeee.feeeeeeee.............
        .............effe2e2e2effeeeeeeeeeeeeeeee.feeeeeeee.............
        .............efff22e22fffeeeeeeceeeeeeeec.feeeeeeec.............
        .............ffef2fef2fefeeeeeecceeeeeeec.fceeeeeec.............
        .............feeffeeefeeeeeeeeefceeeeeeef.fceeeeeef.............
        .............ffeeeeeeeeefeeeeeeffeeeeeeef.efeeeeeef.............
        ............4f44fffffff4eeeeeeeffeeeeeeef.efeeeeeef.............
        ............444df22222fd4eeeeeeeeeeeeeeee.eeeeeeeee.............
        ...........44e44f44444f44eeeeeeeeeeeeeeee.eeeeeeeee.............
        ..........444eeeefffff.eeeeeeeeeeeeeeeeee..eeeeeeee.............
        .....44..444.eeeefeeef.eeeeeeeeeeeeeeeeeef.eeeeeeee.............
        ....444.444..eeeeeeee..eeeeeeeeeeeeeeeeee..eeeeeeee.............
        ...4444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeceeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..444444444..eeceeeee..eeeeeeefeeeeeeeefe..eeeeeefe.............
        ..44444444...eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ..4444444....eeeeeeee..eeeeeeeceeeeeeeece..eeeeeece.............
        ...4444......eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............eeeeeeeee.eeeeeeeeeeeeeeeeeee.eeeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............ceeeeeeef.ceeeeeeeeceeeeeeeef.ceeeeeee.............
        .............fcceeeec..fceeeeeeefceeeecee..feeeecee.............
        .............fccceecc..fcceececefcceeccce..feeeecce.............
        .............fcceeccc..fceeececcfceeccccc..feececcc.............
        .............fccceccc..fcceececcfcceccccc..feececcc.............
        .............fccccece..fccccceccfcccececc..fcceeecc.............
        .............fccccccc..fcccccccffcccccccf..fccccccf.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        .............cccccccc..cccccccccccccccccc..cccccccc.............
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        ................................................................
        `],
    200,
    characterAnimations.rule(Predicate.NotMoving)
    )
}
let raft: Sprite = null
let hero: Sprite = null
let raftVel = 0
let heroVel = 0
let canEnterRaft = false
let canEnterVillage = false
let canEnterRiver = false
let currentTileMap = ""
currentTileMap = "HeroHouse"
tiles.loadMap(tiles.createMap(assets.tilemap`HeroHouse`))
heroVel = 50
raftVel = 50
loadHeroHouse()
game.onUpdateInterval(100, function () {
    // if (currentTileMap == "HeroHouse") {
    // loadHeroHouse()
    // }
    if (currentTileMap == "Sea") {
        loadSea()
    }
    if (currentTileMap == "Village") {
        loadVillage()
    }
})
